type Company {
    id: ID!
    name: String!
    sector: String!
    products: [Product!]!
    goalImpacts: [CompanyGoalImpact!]!
}

extend type Query {
    listCompanies(page: Int! = 1): [Company!]!
    getCompany(id: ID!): Company
    findCompanies(partialName: String!): [Company!]!
}