interface ProductImpact {
    goal: Goal!
    product: Product!
    impactLevel: ImpactLevel!
}

type DirectProductImpact implements ProductImpact {
    goal: Goal!
    product: Product!
    impactLevel: ImpactLevel!
}

type ViaProductImpact implements ProductImpact {
    goal: Goal!
    product: Product!
    viaProduct: Product!
    impactLevel: ImpactLevel!
}
